# Inverse Matriser (MIP 10.7)

De kvadratiske matrisene

$$
\left[\begin{array}{cc}
1 & 0 \\
0 & 1
\end{array}\right],
\quad
\left[\begin{array}{ccc}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{array}\right],
\quad
\text{osv}
$$


er spesielle: Ganges de på en annen matrise $A$ blir resultatet matrisen $A$ selv. 

## Eksempel

$$
\left[\begin{array}{cc}
1 & 0 \\ 0 & 1
\end{array}\right]
\cdot
\left[\begin{array}{cc}
1 & 2 \\ 3 & 4
\end{array}\right]
=
\left[\begin{array}{cc}
1 & 2 \\ 3 & 4
\end{array}\right]
$$
og
$$
\left[\begin{array}{cc}
1 & 2 \\ 3 & 4
\end{array}\right]
\cdot
\left[\begin{array}{cc}
1 & 0 \\ 0 & 1
\end{array}\right]
=
\left[\begin{array}{cc}
1 & 2 \\ 3 & 4
\end{array}\right]
$$


## Oppgave

La $I$ være $3 \times 3$ matrisen
$$
I = 
\left[\begin{array}{ccc}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{array}\right]
$$
La $A$, $B$ og $C$ være $3 \times 3$ matriser slik at 
$$A \cdot B = I \quad \text{og} \quad C \cdot A = I.$$
Bruk regnereglene 
* $B = I \cdot B$,
* $(C \cdot A) \cdot B = C \cdot (A \cdot B)$
* $C \cdot I = C$

til å forklare hvorfor $B = C$.

## Invers matrise

I situasjonen i oppgaven over sier vi at $B$ er den inverse matrisen til $A$, og vi skriver
$$B = A^{-1}$$

## Oppgave

La $A$, $B$ og $C$ være $3 \times 3$ matriser slik at $A \cdot B = I$ og $B \cdot C = I$.
Bruk regnereglene
* $C = I \cdot C$
* $(A \cdot B) \cdot C = A \cdot (B \cdot C)$ og
* $A \cdot I = A$

til å forklare hvorfor $C = A$.

### Bemerkning

Vi blir fortalt at $\det(A \cdot B) = \det(A) \cdot \det(B)$. Dessuten er det ikke vanskelig å sjekke at $\det(I) = 1$. Derfor vet vi at hvis $A \cdot B = I$, da er $\det(A) \cdot \det(B) = 1$, 
så vi vet både at $\det(A) \ne 0$ og at $\det(B) \ne 0$.

## Teorem

Hvis $\det(A) \ne 0$ da har $A$ en invers matrise.

### Begrunnelse:

La oss si at $A$ er en $3 \times 3$ matrise. Siden $\det(A) \ne 0$ ved vi fra Teorem 4 i avsnitt 10.4 i MIP at det 
finnes nøyaktig en løsning 
$$\vec b_1 = 
\left[\begin{array}{c}
b_{11} \\ b_{21} \\ b_{31}
\end{array}\right]
\qquad \text{til ligningssystemet} \qquad
A \cdot \vec b_1 =
\left[\begin{array}{c}
1 \\ 0 \\ 0
\end{array}\right].$$
Tilsvarende
finnes nøyaktig en løsning 
$$\vec b_2 = 
\left[\begin{array}{c}
b_{12} \\ b_{22} \\ b_{32}
\end{array}\right]
\qquad \text{til ligningssystemet} \qquad
A \cdot \vec b_2 =
\left[\begin{array}{c}
0 \\ 1 \\ 0
\end{array}\right].$$
Endelig finnes også nøyaktig en løsning 
$$\vec b_3 = 
\left[\begin{array}{c}
b_{13} \\ b_{23} \\ b_{33}
\end{array}\right]
\qquad \text{til ligningssystemet} \qquad
A \cdot \vec b_3 =
\left[\begin{array}{c}
0 \\ 0 \\ 1
\end{array}\right].$$


Matrisen
$$
B = [\vec b_1\ \vec b_2 \ \vec b_3] = 
\left[\begin{array}{ccc}
b_{11} & b_{12} & b_{13} \\
b_{21} & b_{22} & b_{23} \\
b_{31} & b_{32} & b_{33}
\end{array}\right]$$

er slik at $A \cdot B = I$. (Hvorfor?) Vi vet nå fra bemerkningen over at $\det(B) \ne 0$, så på samme måte kan vi finne en matrise $C$ slik at $B \cdot C = I$.
Fra oppgaven over vet vi at $A = C$, så $B = A^{-1}$.

## Eksempel

$$A =
\left[\begin{array}{ccc}
1 & 1 & 0 \\
0 & 2 & 0 \\
0 & 1 & 1
\end{array}\right]$$

For å finne $\vec b_1$ gjør vi Gauss eliminasjon:

$$
\left[\begin{array}{ccc|c}
1 & 1 & 0 & 1\\
0 & 2 & 0 & 0\\
0 & 1 & 1 & 0
\end{array}\right]
\sim
\left[\begin{array}{ccc|c}
1 & 1 & 0 & 1\\
0 & 1 & 0 & 0\\
0 & 1 & 1 & 0
\end{array}\right]
\begin{array}{c}
\phantom{A} \\
\mathrm{II}/2 \newline
\phantom{A}
\end{array}
\sim
\left[\begin{array}{ccc|c}
1 & 0 & 0 & 1\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0
\end{array}\right]
\begin{array}{c}
\mathrm{I} - \mathrm{II} \\
\phantom{\mathrm{II}/2} \newline
\mathrm{III} - \mathrm{II} 
\end{array}
$$


som gir
$\vec b_1 = 
\left[\begin{array}{c}
1 \\ 0 \\0
\end{array}\right]$

For å finne $\vec b_2$ gjør vi igjen Gauss eliminasjon:

$$
\left[\begin{array}{ccc|c}
1 & 1 & 0 & 0\\
0 & 2 & 0 & 1\\
0 & 1 & 1 & 0
\end{array}\right]
\sim
\left[\begin{array}{ccc|c}
1 & 1 & 0 & 0\\
0 & 1 & 0 & 1/2\\
0 & 1 & 1 & 0
\end{array}\right]
\begin{array}{c}
\phantom{A} \\
\mathrm{II}/2 \newline
\phantom{A}
\end{array}
\sim
\left[\begin{array}{ccc|c}
1 & 0 & 0 & -1/2\\
0 & 1 & 0 & 1/2\\
0 & 0 & 1 & -1/2
\end{array}\right]
\begin{array}{c}
\mathrm{I} - \mathrm{II} \\
\phantom{\mathrm{II}/2} \newline
\mathrm{III} - \mathrm{II} 
\end{array}
$$


som gir
$\vec b_2 = 
\left[\begin{array}{c}
-1/2 \\ 1/2 \\ -1/2
\end{array}\right]$

På helt samme måte fås $\vec b_3 = 
\left[\begin{array}{c}
0 \\ 0 \\ 1
\end{array}\right]$:

$$
\left[\begin{array}{ccc|c}
1 & 1 & 0 & 0\\
0 & 2 & 0 & 0\\
0 & 1 & 1 & 1
\end{array}\right]
\sim
\left[\begin{array}{ccc|c}
1 & 1 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 1 & 1 & 1
\end{array}\right]
\begin{array}{c}
\phantom{A} \\
\mathrm{II}/2 \newline
\phantom{A}
\end{array}
\sim
\left[\begin{array}{ccc|c}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & -1
\end{array}\right]
\begin{array}{c}
\mathrm{I} - \mathrm{II} \\
\phantom{\mathrm{II}/2} \newline
\mathrm{III} - \mathrm{II} 
\end{array}
$$


Den inverse matrisen til $A$ er altså

$$A^{-1} = 
\left[\begin{array}{ccc}
1 & -1/2 & 0 \\
0 & 1/2 & 0 \\
0 & -1/2 & 1
\end{array}\right]$$

## Forenkling

Vi kan gjøre alle Gauss eliminasjonene samtidig ved å jobbe med en større matrise:

$$
\left[\begin{array}{ccc|ccc}
1 & 1 & 0 & 1 & 0 & 0\\
0 & 2 & 0 & 0 & 1 & 0\\
0 & 1 & 1 & 0 & 0 & 1
\end{array}\right]
\sim
\left[\begin{array}{ccc|ccc}
1 & 1 & 0 & 0 & 1 & 0\\
0 & 1 & 0 & 0 & 1/2 & 0\\
0 & 1 & 1 & 0 & 0 & 1
\end{array}\right]
\begin{array}{c}
\phantom{A} \\
\mathrm{II}/2 \newline
\phantom{A}
\end{array}
\sim
\left[\begin{array}{ccc|ccc}
1 & 0 & 0 & 1 & -1/2 & 0\\
0 & 1 & 0 & 0 & 1/2 & 0\\
0 & 0 & 1 & 0 & -1/2 & 1
\end{array}\right]
\begin{array}{c}
\mathrm{I} - \mathrm{II} \\
\phantom{\mathrm{II}/2} \newline
\mathrm{III} - \mathrm{II} 
\end{array}
$$


## Beregning av invers ved hjelp av python

Vi har allerede sett en python funksjon som kan gjøre Gauss Jordan eliminasjon. Denne funksjonen kan regne ut inverse matriser for oss.

In [1]:
import numpy as np

In [2]:
def normer_forste_element(a):
    # Finn indeksen til det første elementet i vektoren a som ikke er null
    forste_ikke_null_element_indeks = np.argmax(a != 0)
    
    # Hent verdien til det første ikke-null elementet
    forste_ikke_null_element = a[forste_ikke_null_element_indeks]
    
    # Returner den normaliserte vektoren, der alle elementer er delt på det første ikke-null elementet
    return a / forste_ikke_null_element
    
def gauss_jordan(A):
    # Hvis matrisen kun består av nuller, returner den uendret
    if np.all(A == 0):
        return A
    
    # Hvis matrisen har én rad, normaliser den første radens første ikke-null element
    elif len(A) == 1:
        A[0] = normer_forste_element(A[0])
        return A
    else:
        # Beregn radenes summer for å normalisere matrisen 
        # (Dette er ikke nødvendig, men gjør tallene finere å regne med)
        rad_summer = np.sum(A, axis=1)
        A = A / rad_summer[:, None]  # Normaliser hver rad ved å dele med radens sum
        
        # Finn kolonner som inneholder ikke-null elementer
        ikke_null_kolonner = np.any(A != 0, axis=0)
        
        # Finn indeksen til den første kolonnen med ikke-null elementer
        forste_ikke_null_kolonne_indeks = np.argmax(ikke_null_kolonner)
        
        # Finn indeksen til raden med største verdi i den valgte kolonnen (pivot rad)
        pivot_rad_indeks = np.argmax(A[:, forste_ikke_null_kolonne_indeks])
        
        # Normaliser pivot raden
        pivot_rad = normer_forste_element(A[pivot_rad_indeks])
        
        # Bytt plass på pivot raden og den første raden
        A[pivot_rad_indeks] = A[0]
        A[0] = pivot_rad
        
        # Utfør eliminering for å gjøre alle elementene under pivoten null
        A[1:] = A[1:] - (A[1:, 0] / A[0, 0])[:, None] * A[0][None, :]
        
        # Kall gauss_jordan rekursivt på den nedre delmatrisen
        A[1:, 1:] = gauss_jordan(A[1:, 1:])
        
        # Gjør den første raden null over pivot-posisjonene til de øvrige radene.
        for rad in A[1:]:
            if np.any(rad != 0):  # Hvis raden ikke er null
                # Finn indeksen til det første ikke-null elementet i raden
                forste_ikke_null_element_indeks = np.argmax(rad != 0)
                
                # Trekk et tall gange den akutelle raden fra den første raden slik at første raden blir null over
                # pivot-elementet til den aktuelle raden
                A[0] = A[0] - (A[0, forste_ikke_null_element_indeks] / rad[forste_ikke_null_element_indeks]) * rad
    
    # Returner den resulterende matrisen
    return A


Vi skriver matrisen fra før inn i python som en numpy array.

$$
AI = \left[\begin{array}{cccccc}
1 & 1 & 0 & 1 & 0 & 0\\
0 & 2 & 0 & 0 & 1 & 0\\
0 & 1 & 1 & 0 & 0 & 1
\end{array}\right]
$$


In [3]:
AI = np.array([
    [1, 1, 0, 1, 0, 0],
    [0, 2, 0, 0, 1, 0],
    [0, 1, 1, 0, 0, 1]
])

In [4]:
gauss_jordan(AI)

array([[ 1. ,  0. ,  0. ,  1. , -0.5,  0. ],
       [ 0. ,  1. ,  0. ,  0. ,  0.5,  0. ],
       [ 0. ,  0. ,  1. ,  0. , -0.5,  1. ]])

Her kan vi igjen lese av den inverse matrisen til $A$ fra høyre halvden av denne matrisen.

## Funksjon som regner ut invers matrise

Vi leste av den inverse matrisen til en matrise $A$ fra Gauss Jordan eliminasjonen av $A$. I stedet for skrive av resultatet for hånd kan vi lage en 
python funksjon som finner den inverse matrisen for oss.

In [5]:
def invers_matrise(A):
    assert A.shape[0] == A.shape[1], "matrisen A skal være kvadratisk"
    B = gauss_jordan(np.hstack([A, np.eye(A.shape[0])]))
    return B[:, B.shape[0]:]

In [6]:
A = np.array([
    [1, 1, 0],
    [0, 2, 0],
    [0, 1, 1]
])

In [7]:
invers_matrise(A)

array([[ 1. , -0.5,  0. ],
       [ 0. ,  0.5,  0. ],
       [ 0. , -0.5,  1. ]])

## Numpy invers matrise 

Numpy kan regne ut inverse matriser for oss ved hjelp av funksjonen "solve" som vist under.

In [8]:
np.linalg.solve(A, np.eye(A.shape[0]))

array([[ 1. , -0.5,  0. ],
       [ 0. ,  0.5,  0. ],
       [ 0. , -0.5,  1. ]])