# Gauss Jordan eliminasjon (MIP 10.4)

## Eksempel

Se på
$$
\begin{align}
2x + 3y  &= 5 \newline
4x + 5y &= 9
\end{align}
$$

Bemerk at følgende manipulasjoner ikke vil endre på løsningene til systemet
1. ta et tall gange den ene raden og leg til den andre raden
2. bytt om rader
3. gang en rad med et tall $\ne 0$

La os gjøre dette:

Trekk to ganger den første raden fra den andre raden og få:
$$
\begin{matrix}
2x & + & 3y  &=& 5 \newline
   &-& y &=& -1
\end{matrix}
$$

Legg nå tre ganger den andre raden til den første raden og få:
$$
\begin{matrix}
2x &  &   &=& 2 \newline
   &-& y &=& -1
\end{matrix}
$$

Gang til slutt første raden med en halv og andre raden med minus en:
$$
\begin{matrix}
x &  &   &=& 1 \newline
   && y &=& 1
\end{matrix}
$$

## Skjematisk form

Siden symbolene $x$ og $y$ hver gang står på samme posisjon i ligningssystemene kan vi la dem være innforståtte og skrive regningen over på skjematisk form:

$$
\left[\begin{array}{cc|c} 
   2 & 3 & 5  \\
   4 & 5 & 9 
\end{array}\right]
\sim
\left[\begin{array}{cc|c} 
   2 & 3 & 5  \\
   0 & -1 & -1 
\end{array}\right]
\begin{array}{c} 
     \\
   \mathrm{II} - 2 \mathrm{I}
\end{array}
\sim
\left[\begin{array}{cc|c} 
   2 & 0 & 2  \\
   0 & -1 & -1 
\end{array}\right]
\begin{array}{c}
\mathrm{I} + 3\mathrm{II} \newline
\phantom{A}
\end{array}
\sim
\left[\begin{array}{cc|c} 
   1 & 0 & 1  \\
   0 & 1 & 1 
\end{array}\right]
\begin{array}{c}
\frac 12 \cdot \mathrm{I} \newline
\phantom{A}
\end{array}
$$

Dette kan leses av som
$$
\begin{array}{ccccc} 
   x & + & 0 & = & 1  \\
   0 & + & y & = & 1 
\end{array}
$$

### Eksempel

Se på ligningssystemet
$$
\begin{array}{ccccccccccc}
    3x_0 &+& x_1& +& 3x_2& +& x_3 &+ &4x_4& = &2 \\
    4x_0 &+& x_1 & + &4x_2 &+ &x_3& + &5x_4 &= &3
\end{array}
$$

Som over kan vi "redusere" systemet på skjematisk form:

$$
\left[
\begin{array}{ccccc|c}
  3 & 1 & 3 & 1 & 4 & 2 \\
  4 & 1 & 4 & 1 & 5 & 3
\end{array}
\right]
\sim
\left[
\begin{array}{ccccc|c}
  3 & 1 & 3 & 1 & 4 & 2 \\
  0 & -1/3 & 0 & -1/3 & -1/3 & 1/3
\end{array}
\right]
\begin{array}{c}
\\
\mathrm{II} - 4\mathrm{I}/3
\end{array}
\sim
\left[
\begin{array}{ccccc|c}
  3 & 1 & 3 & 1 & 4 & 2 \\
  0 & 1 & 0 & 1 & 1 & -1
\end{array}
\right]
\begin{array}{c}
\\
-3\mathrm{II}
\end{array}
\sim
\left[
\begin{array}{ccccc|c}
  3 & 0 & 3 & 0 & 3 & 3 \\
  0 & 1 & 0 & 1 & 1 & -1 
\end{array}
\right]
\begin{array}{c}
\mathrm{I} -
\mathrm{II}\\
\phantom{ }
\end{array}
\sim
\left[
\begin{array}{ccccc|c}
  1 & 0 & 1 & 0 & 1 & 1 \\
  0 & 1 & 0 & 1 & 1 & -1 
\end{array}
\right]
\begin{array}{c}
\mathrm{I}/3
\\
\phantom{ }
\end{array}
$$

Setter vi inn de ukjente fås det ekvivalente systemet:
$$
\begin{array}{ccccccccccc}
    x_0 &+& & & x_2& +& &&x_4& = &1 \\
     && x_1 & + & & &x_3& + &x_4 &= &-1
\end{array}
$$

Her er det uendelig mange løsninger. Uansett hvilke verdier $x_2$, $x_3$ og $x_4$ får vi en løsning ved å sette $x_0 = 1 - x_2 - x_4$ og $x_1 = -1 - x_3 - x_4$.

## Målet med Gauss Jordan eliminasjon

På første rad vil vi ha et ettall så langt til venstre som mulig og nuller under det. Deretter vil vi på andre rad ha et ettall så langt til venstre som mulig og nuller under og over det. Sådan fortsettes med resten av radene.

## Python kode

In [1]:
import numpy as np

def normer_forste_element(vektor):
    """
    Normaliserer en vektor ved å dele alle elementer på det første ikke-null elementet.
    
    Parametere:
        vektor (np.ndarray): En 1D Numpy-array som skal normaliseres.
    
    Returnerer:
        np.ndarray: En normalisert vektor der det første ikke-null elementet er 1.
    """
    # Finn indeksen til det første elementet i vektoren som ikke er null
    forste_ikke_null_indeks = np.argmax(vektor != 0)
    
    # Hent verdien til det første ikke-null elementet
    forste_ikke_null_element = vektor[forste_ikke_null_indeks]
    
    # Returner den normaliserte vektoren
    return vektor / forste_ikke_null_element

def gauss_jordan(matrise, epsilon=1e-8):
    """
    Utfører Gauss-Jordan eliminasjon på en gitt matrise.
    
    Parametere:
        matrise (np.ndarray): En 2D Numpy-array som representerer matrisen.
        epsilon (float): En liten verdi for å håndtere numerisk presisjon.
    
    Returnerer:
        np.ndarray: En rekkeredusert matrise i redusert trappeform.
    """
    # Sett svært små verdier til null for å unngå numeriske feil
    matrise[np.abs(matrise) < epsilon] = 0
    
    # Hvis matrisen kun består av nuller, returner den uendret
    if np.all(matrise == 0):
        return matrise
    
    # Hvis matrisen har én rad, normaliser den første radens første ikke-null element
    elif len(matrise) == 1:
        matrise[0] = normer_forste_element(matrise[0])
        return matrise
    
    # Beregn radenes summer for å normalisere matrisen (gjør tallene mer håndterbare)
    rad_maksimummer = np.max(np.abs(matrise), axis=1)
    matrise = matrise / rad_maksimummer[:, None]  # Normaliser hver rad
    
    # Finn kolonner som inneholder ikke-null elementer
    ikke_null_kolonner = np.any(matrise != 0, axis=0)
    
    # Finn indeksen til den første kolonnen med ikke-null elementer
    forste_ikke_null_kolonne = np.argmax(ikke_null_kolonner)
    
    # Finn indeksen til raden med største verdi i den valgte kolonnen (pivot rad)
    pivot_rad_indeks = np.argmax(matrise[:, forste_ikke_null_kolonne])
    
    # Normaliser pivot-raden
    pivot_rad = normer_forste_element(matrise[pivot_rad_indeks])
    
    # Bytt plass på pivot-raden og den første raden
    matrise[pivot_rad_indeks] = matrise[0]
    matrise[0] = pivot_rad
    
    # Utfør eliminering for å gjøre alle elementene under pivoten null
    matrise[1:] -= (matrise[1:, 0] / matrise[0, forste_ikke_null_kolonne])[:, None] * matrise[0]
    
    # Kall Gauss-Jordan rekursivt på den nedre delmatrisen
    matrise[1:, 1:] = gauss_jordan(matrise[1:, 1:])
    
    # Gjør den første raden null over pivot-posisjonene til de øvrige radene.
    for rad in matrise[1:]:
        if np.any(rad != 0):  # Hvis raden ikke er null
            # Finn indeksen til det første ikke-null elementet i raden
            forste_ikke_null_kolonne = np.argmax(rad != 0)
            
            # Trekk fra et multiplum av denne raden for å gjøre elementet over pivot null
            matrise[0] -= (matrise[0, forste_ikke_null_kolonne] / rad[forste_ikke_null_kolonne]) * rad
    
    # Returner den resulterende matrisen
    return matrise


## Eksempel

Se på ligningssystemet
$$
\begin{array}{ccccccccccc}
    3x_0 &+& x_1& +& 3x_2& +& x_3 &+ &4x_4& = &2 \\
    3x_0 &+& x_1& +& 3x_2& +& x_3 &+ &4x_4& = &1
\end{array}
$$

Vi ser umiddelbart at dette ikke kan gå bra siden det er umulig å ha $2 = 1$.

La oss likevel se hva som skjer når vi prøver å "redusere" dette systemet på skjematisk form:

$$
\left[
\begin{array}{ccccc|c}
  3 & 1 & 3 & 1 & 4 & 2 \\
  3 & 1 & 3 & 1 & 4 & 1 
\end{array}
\right]
\sim
\left[
\begin{array}{ccccc|c}
  3 & 1 & 3 & 1 & 4 & 2 \\
  0 & 0 & 0 & 0 & 0 & -1
\end{array}
\right]
\begin{array}{c}
\\
\mathrm{II} - \mathrm{I}
\end{array}
\sim
\left[
\begin{array}{ccccc|c}
  1 & 1/3 & 1 & 1/3 & 4/3 & 2/3 \\
  0 & 0 & 0 & 0 & 0 & -1
\end{array}
\right]
\begin{array}{c}
\mathrm{I} / 3
\\
\phantom{ }
\end{array}
$$

Her er vi kommet frem til at hvis ligningssystemet har en løsning da er $0 = -1$. Siden det ikke er riktig har systemet ingen løsning!

In [2]:
# La oss bruke koden vår på denne matrisen

A = np.array([
    [3, 1, 3, 1, 4, 2],    
    [3, 1, 3, 1, 4, 1]
])

gauss_jordan(A)

array([[ 1.        ,  0.33333333,  1.        ,  0.33333333,  1.33333333,
         0.        ],
       [ 0.        , -0.        , -0.        , -0.        , -0.        ,
         1.        ]])

## Kode som leser av den utvidede reduserte matrisen og gir løsninger

In [3]:
def pivot_posisjoner(matrise):
    """
    Finner pivotposisjonene i en rekkeredusert matrise.
    """
    pivot_sett = set()
    pivot_rader = []
    pivot_kolonner = []
    for rad_indeks, rad in enumerate(matrise):
        if np.any(rad != 0):
            første_ikke_null_kolonne = np.argmax(rad != 0)
            pivot_rader.append(rad_indeks)
            pivot_kolonner.append(første_ikke_null_kolonne)
    return pivot_rader, pivot_kolonner

def frie_parametre(matrise):
    """
    Finner bundne og frie parametere i en rekkeredusert matrise.
    """
    _, pivot_kolonner = pivot_posisjoner(matrise)
    alle_kolonner = set(range(matrise.shape[1]))
    return sorted(alle_kolonner.difference(pivot_kolonner))

def null_rom(matrise):
    """
    Finner en basis for nullrommet til en matrise.
    """
    nullrom_basis = []
    redusert_matrise = gauss_jordan(matrise)
    pivot_rader, pivot_kolonner = pivot_posisjoner(redusert_matrise)
    frie = frie_parametre(redusert_matrise)
    
    for fri in frie:
        vektor = np.zeros((matrise.shape[1], 1))
        vektor[fri] = 1
        for rad, kolonne in zip(pivot_rader, pivot_kolonner):
            vektor[kolonne] = -np.sum((redusert_matrise @ vektor)[rad])
        nullrom_basis.append(vektor)
    
    return nullrom_basis

def partikulaer_losning(koeffisientmatrise, høyreside=None):
    """
    Finner en partikulær løsning til ligningssystemet Ax = b.
    """
    if høyreside is None:
        høyreside = np.zeros(koeffisientmatrise.shape[1])
    if len(høyreside.shape) == 1:
        høyreside = høyreside[:, None]
    
    utvidet_matrise = gauss_jordan(np.hstack([koeffisientmatrise, høyreside]))
    radindekser, kolonneindekser = pivot_posisjoner(utvidet_matrise[:, :-1])
    løsning = np.zeros((koeffisientmatrise.shape[1], 1))
    redusert_høyreside = utvidet_matrise[:, -1]
    
    for rad, kolonne in zip(radindekser, kolonneindekser):
        løsning[kolonne] = redusert_høyreside[rad]

    assert np.allclose(koeffisientmatrise @ løsning[None, :], høyreside), "Det finnes ingen løsning til det lineære ligningssystemet"
    return løsning


## Eksempel

Se på
$$
\begin{align}
2x + 3y  &= 5 \newline
4x + 5y &= 9
\end{align}
$$

Vi kan løse dette med koden vår slik som dette:

In [4]:
A = np.array([
    [2, 3],
    [4, 5]
])

b = np.array([5, 9])

In [5]:
x = partikulaer_losning(A, b)

In [6]:
A @ x

array([[5.],
       [9.]])

For å vite hvor mange løsninger det finnes kan vi se på nullrommet

In [7]:
null_rom(A)

[]

Dette betyr at nullvektoren $0$ er eneste vektor $\vec v$ med $A \cdot \vec = 0$ 

## Eksempel

Se på ligningssystemet
$$
\begin{array}{ccccccc}
    1x_0 &+& 2x_1& +& 3x_2& = &2 \\
    4x_0 &+& 5x_1& +& 6x_2& = &5 \\
    7x_0 &+& 8x_1& +& 9x_2& = &8 
\end{array}
$$


Gauss Jordan reduksjon blir

$$
\left[
\begin{array}{ccc|c}
    1 & 2 & 3 & 2 \\
    4 & 5 & 6 & 5 \\
    7 & 8 & 9 & 8
\end{array}
\right]
\sim
\left[
\begin{array}{ccc|c}
    1 & 2 & 3 & 2 \\
    0 & -3 & -6 & -3 \\
    0 & -6 & -12 & -6
\end{array}
\right]
\begin{array}{c}
    \\
    \mathrm{II} - 4\mathrm{I} \\
    \mathrm{III} - 7\mathrm{I} 
\end{array}
\sim
\left[
\begin{array}{ccc|c}
    1 & 2 & 3 & 2 \\
    0 & 1 & 2 & 1 \\
    0 & 0 & 0 & 0
\end{array}
\right]
\begin{array}{c}
    \\
    -\mathrm{II}/3\\
    \mathrm{III} - 2\mathrm{II} 
\end{array}
\sim
\left[
\begin{array}{ccc|c}
    1 & 0 & -1 & 0 \\
    0 & 1 & 2 & 1 \\
    0 & 0 & 0 & 0
\end{array}
\right]
\begin{array}{c}
    \mathrm{I} - 2\mathrm{II}\\ 
    \phantom{A}\\
    \phantom{A}
\end{array}
$$

Her leser vi av
$$
\begin{array}{cccccccc}
    x_0 &-& & & x_2& = &0 \\
     && x_1& +& 2x_2& = &1 \\
    &&&&0& = &0 
\end{array}
$$

Uansett verdien til $x_2$ har vi en løsning der $x_0 = x_2$ og $x_1 = 1 - 2x_2$.

Her skriver vi igjen inn koeffisientmatrisen og høyresiden:

In [8]:
A = np.array([
    [1., 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = np.array([2, 5, 8])

In [9]:
x = partikulaer_losning(A, b)

In [10]:
x

array([[0.],
       [1.],
       [0.]])

In [11]:
A @ x

array([[2.],
       [5.],
       [8.]])

In [12]:
null_rom_for_A = null_rom(A)

In [13]:
null_rom_for_A

[array([[ 1.],
        [-2.],
        [ 1.]])]

Vi ser at det er en vektor $\vec v$ forskjellig fra nullvektoren slik at $A \cdot \vec v = 0$

In [14]:
v = null_rom_for_A[0]
v

array([[ 1.],
       [-2.],
       [ 1.]])

In [15]:
A @ v

array([[0.],
       [0.],
       [0.]])

Siden $A \cdot \vec v = \vec 0$ har vi $A \cdot(\vec x + x_2 \vec v) = A \cdot \vec x + x_2 A \cdot \vec v = A \cdot \vec x
+ x_2 \vec 0 = A \cdot \vec x = \vec b$ der 
$$\vec x + x_2 \vec v =
\left[\begin{array}{c}
0 \\ 1 \\ 0 \end{array}\right]
+
x_2
\left[\begin{array}{c}
1 \\ -2 \\ 1 \end{array}\right]
=
\left[\begin{array}{c}
x_2 \\ 1 - 2x_2 \\ x_2 \end{array}\right]
$$
Dette er de samme løsningene som vi fant for hånd.

## Eksempel

Se på ligningssystemet
$$
\begin{array}{ccccccccccc}
    3x_0 &+& x_1& +& 3x_2& +& x_3 &+ &4x_4& = &2 \\
    3x_0 &+& x_1& +& 3x_2& +& x_3 &+ &4x_4& = &1
\end{array}
$$

In [16]:
A = np.array([
    [3, 1, 3, 1, 4],
    [3, 1, 3, 1, 4],
])

b = np.array([2, 1])

In [17]:
partikulaer_losning(A, b)

AssertionError: Det finnes ingen løsning til det lineære ligningssystemet

Dette ser farlig ut, men egentlig er det akkurat hva vi til ha. **Det finnes ingen løsning!**